version: 2
jobs:
  build:
    docker:
      - image: hashicorp/packer:1.3.3
    steps:
      - checkout
      - run:
          name: packer build
          command: |
            packer build build.json
workflows:
  version: 2
  plan_apply:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
