#!/bin/bash
#
# railsapp

# chkconfig: 2345 82 55
# processname: sample-app
# description: Runs railsapp for nginx integration.

# Include RedHat function library
. /etc/rc.d/init.d/functions

# The name of the service
NAME=sample-app

# The username and path to the myapp source
USER=ec2-user
APP_PATH=/opt/sample-app

# The PID and LOCK files used by puma and sidekiq
UPID=$APP_PATH/tmp/puma.pid
ULOCK=/var/lock/subsys/$NAME

# The options to use when running puma
#OPTS="-F $APP_PATH/config/puma.rb"

# Ruby related path update
RUBY_PATH_PATCH="PATH=$PATH:/usr/local/lib/dev/ruby/bin && export PATH && "
BUNDLE_CMD=bundle
PUMA_CMD=pumactl

start() {
  cd $APP_PATH
  # Start puma
  echo -n $"Starting $NAME: "
  PATH=/usr/local/lib/dev/ruby/bin:/usr/local/lib/dev/node/bin:$PATH puma -C $APP_PATH/config/puma.rb -d
  puma=$?
  [ $puma -eq 0 ] && touch $ULOCK
  echo

  return $puma
}

stop() {
  cd $APP_PATH

  # Stop puma
  echo -n $"Stopping $NAME: "
  killproc -p $UPID
  puma=$?
  [ $puma -eq 0 ] && rm -f $ULOCK
  echo

  return $puma
}

restart() {
  stop
  start
}

get_status() {
  status -p $UPID $NAME
}

query_status() {
  get_status >/dev/null 2>&1
}

case "$1" in
  start)
    query_status && exit 0
    start
    ;;
  stop)
    query_status || exit 0
    stop
    ;;
  restart)
    restart
    ;;
  status)
    get_status
    exit $?
    ;;
  *)
    N=/etc/init.d/$NAME
    echo "Usage: $N {start|stop|restart|status}" >&2
    exit 1
    ;;
esac

exit 0