- name: create ruby dir
  file:
    path: "/usr/local/lib/dev/ruby"
    state: directory
    owner: ec2-user
    group: ec2-user

- name: install ruby
  become: yes
  become_user: ec2-user
  shell: "/opt/xbuild/ruby-install {{ ruby_version }} /usr/local/lib/dev/ruby"

- name: set path
  become_user: ec2-user
  lineinfile: >
    dest="~/.bash_profile"
    line="export PATH=/usr/local/lib/dev/ruby/bin:$PATH"

- name: install bundler
  become_user: "ec2-user"
  gem:
    name: bundler
    executable: /usr/local/lib/dev/ruby/bin/gem
    version: "{{ bundler_version }}"